### ISSUE TITLE
Install-Automate throwing error after update to v2020.9

### ISSUE THREAD

**Issue by DanFDC** [Braingears/PowerShell#4]
I've been using this script successfully since we deployed until the last update.  Now when I run the script I get the error: The Automate Server or Token Parameters Was Not Entered or Inaccessible

Original script provided: Invoke-Expression(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/Braingears/PowerShell/master/Automate-Module.psm1'); Install-Automate -Server 'automate.genericservername.com' -LocationID 2 -Transcript

**Comment by Braingears** [comment]
Due to security changes made by ConnectWise, the script now requires -Token. 
Get-Help Install-Automate
